version: '3'
services:

  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    network_mode: bridge
    container_name: postgres
    environment:
      POSTGRES_USER: 'odoo'
      POSTGRES_PASSWORD: 'odoopass'
      POSTGRES_DB: 'postgres'
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
